### ISSUE TITLE
deprecated url

### ISSUE THREAD

**Issue by Abdel-had** [eazytraining/openshift-administrator-training#1]
![image](https://github.com/eazytraining/openshift-administrator-training/assets/101605739/229db6a4-21bb-4cbc-adf8-bc7db52d5676)

https://mirror.almalinux.ikoula.com/8.7/README.txt

At this step :
 
![image](https://github.com/eazytraining/openshift-administrator-training/assets/101605739/40269a2c-adbb-4e19-b3ce-a3c272a4cefc)

https://github.com/eazytraining/openshift-administrator-training/blob/main/tp0-prerequisites/README.md

**Comment by Abdel-had** [comment]
Next available download link is : https://mirror.almalinux.ikoula.com/8.8/isos/x86_64/AlmaLinux-8.8-x86_64-minimal.iso

🙂

**Comment by Abdel-had** [comment]
Best regards

**Comment by diranetafen** [comment]
merged !
