### ISSUE TITLE
Can't find this ansible role named basic-server

### ISSUE THREAD

**Issue by Abdel-had** [eazytraining/openshift-administrator-training#5]
![image](https://github.com/eazytraining/openshift-administrator-training/assets/101605739/e77e5fe7-f43e-408f-af39-0ac8b8689a95)

![image](https://github.com/eazytraining/openshift-administrator-training/assets/101605739/bde356b9-7a26-4046-9d49-c7150f812d6e)

https://github.com/eazytraining/openshift-administrator-training/blob/main/tp1-installation-okd4.10/README.md#configure-environmental-services

**Comment by diranetafen** [comment]
merged ! thanks again !

**Comment by diranetafen** [comment]
merged ! thanks again !
